config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :books
  end

  root 'admin/books#index'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/book.rb
class Admin::Book < ActiveRecord::Base
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :set_admin_book, only: [:show, :edit, :update, :destroy]

  # GET /admin/books
  # GET /admin/books.json
  def index
    @admin_books = Admin::Book.all
  end

  # GET /admin/books/1
  # GET /admin/books/1.json
  def show
  end

  # GET /admin/books/new
  def new
    @admin_book = Admin::Book.new
  end

  # GET /admin/books/1/edit
  def edit
  end

  # POST /admin/books
  # POST /admin/books.json
  def create
    @admin_book = Admin::Book.new(admin_book_params)

    respond_to do |format|
      if @admin_book.save
        format.html { redirect_to @admin_book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @admin_book }
      else
        format.html { render :new }
        format.json { render json: @admin_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/books/1
  # PATCH/PUT /admin/books/1.json
  def update
    respond_to do |format|
      if @admin_book.update(admin_book_params)
        format.html { redirect_to @admin_book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_book }
      else
        format.html { render :edit }
        format.json { render json: @admin_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/books/1
  # DELETE /admin/books/1.json
  def destroy
    @admin_book.destroy
    respond_to do |format|
      format.html { redirect_to admin_books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_book
      @admin_book = Admin::Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_book_params
      params.require(:admin_book).permit(:title, :author)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/books/_form.html.erb
<%= form_for(@admin_book) do |f| %>
  <% if @admin_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_book.errors.count, "error") %> prohibited this admin_book from being saved:</h2>

      <ul>
      <% @admin_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h1>Editing admin_book</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_book %> |
<%= link_to 'Back', admin_books_path %>

app/views/admin/books/index.html.erb
<h1>Listing admin_books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_books.each do |admin_book| %>
      <tr>
        <td><%= admin_book.title %></td>
        <td><%= admin_book.author %></td>
        <td><%= link_to 'Show', admin_book %></td>
        <td><%= link_to 'Edit', edit_admin_book_path(admin_book) %></td>
        <td><%= link_to 'Destroy', admin_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_admin_book_path %>

app/views/admin/books/new.html.erb
<h1>New admin_book</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_books_path %>

app/views/admin/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @admin_book.author %>
</p>

<%= link_to 'Edit', edit_admin_book_path(@admin_book) %> |
<%= link_to 'Back', admin_books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraftingRailsSamples</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>